id: 1a29fe6e14504044b13206d2c84331fb
title: Toh_298-The_Gandi_Sutra-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-071-012
  eft-text-version: 1.1.3 2020
